Create a gallery
amitark7/Gallery-JS pull request #1
Opened 2024-04-05 13:54 UTC by amitark7

2024-04-06 10:19 UTC, amrit56789 commented on index.js
> +const imagesElement = imagesArray.map(
change variable name createImageElement.

2024-04-08 05:05 UTC, meanstack9716 requested changes

2024-04-08 05:05 UTC, meanstack9716 commented on index.css
> +    position: relative;
add tailwind class for this

2024-04-08 05:05 UTC, meanstack9716 commented on index.css
> +    width: 100%;
add tailwind class for this

2024-04-08 05:05 UTC, meanstack9716 commented on index.css
> +    height: 100vh;
add tailwind class for this

2024-04-08 05:05 UTC, meanstack9716 commented on index.css
> +    width: 100%;
add tailwind class for this

2024-04-08 05:05 UTC, meanstack9716 commented on index.css
> +    height: 100vh;
add tailwind class for this

2024-04-08 05:05 UTC, meanstack9716 commented on index.css
> +    background-color: black;
add tailwind class for this

2024-04-08 05:05 UTC, meanstack9716 commented on index.css
> +    position: absolute;
add tailwind class for this

2024-04-08 05:05 UTC, meanstack9716 commented on index.css
> +    position: absolute;
add tailwind class for this

2024-04-08 05:05 UTC, meanstack9716 commented on index.css
> +    width: 60%;
add tailwind class for this

2024-04-08 05:05 UTC, meanstack9716 commented on index.css
> +    left: 20%;
add tailwind class for this

2024-04-08 05:05 UTC, meanstack9716 commented on index.css
> +    top: 10%;
add tailwind class for this

2024-04-08 05:05 UTC, meanstack9716 commented on index.css
> +    width: 100%;
add tailwind class for this

2024-04-08 05:05 UTC, meanstack9716 commented on index.css
> +    cursor: pointer;
all these add tailwind class for this

2024-04-08 05:05 UTC, meanstack9716 commented on index.html
> +                <img src="https://caring-painddt.surge.sh/images/Images1.jpg" class="w-full h-full " alt="popupimages"
use local image

2024-09-12 05:39 UTC, merged